### ISSUE TITLE
Line breaks instead of paragraph

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1111]
(Original issue 1407 created by gargoylesoft on 2017-12-20T06:49:57.823421+00:00)

I'm copying a section of code from Xcode and then running this command in the terminal:

pbpaste | pygmentize -l swift -f rtf -O style=xcode | pbcopy -Prefer rtf

When I then paste into Pages for Mac all of the newlines are being set as Paragraph inserts instead of line inserts, so I have to manually go and change them all.  Is there a way to fix this from pygments?

**Comment by akraus53** [comment]
I also have this issue, currently looking into why this happens

**Comment by akraus53** [comment]
So it seems (!!!!) this is due to the `\sa` keyword not being used. This stands for "space after" (in twips) and defaults to 200, which is 10pt. if we set `\sa0` in [line 116 of the formatter](https://github.com/pygments/pygments/blob/0f3ddb3a6e3ed99957fe20aab695446f85835387/pygments/formatters/rtf.py#L116) this issue doesn't occur anymore. If anyone can double-check this again, I'd be thankful tho.

**Comment by akraus53** [comment]
Update: As it seems, most editors follow the default "\sa0" which is referenced in this beautiful [documentation](https://www.biblioscape.com/rtf15_spec.htm) but Powerpoint doesn't. Setting this default explicitly will not have any negative impact on the functionality. I'll create a pull request really quick.

**Comment by Anteru** [comment]
Fixed in 544e58c5f356fdb7b58b504ae088442f6c81bdcb
