### ISSUE TITLE
DjangoJavascript parsing regex statement wrong

### ISSUE THREAD

**Issue by boanergies** [pygments/pygments#1596]
When I want to run the lexer over a statement like this:

`string = string.replace(/{{ regex }}/g, "{{ char_replace }}");`

For some reason the `/.../g` gets marked as a single line comment instead of a regex statement in javascript. From playing around a bit with the lexers my guess is it has to do with the fact that the django lexer marks the template first as a Comment.Preproc and then the Javascript lexer skips over the already parsed data and sees only a  `//` from it's perspective and marks the rest of the line as a single line comment. Is that correct or am I missing something? If so what would need to change to fix this because I feel like this is the expected behavior from the lexers working together.

**Comment by birkenfeld** [comment]
Your analysis is correct.

It's not easy to fix this, though: on one hand, the template tags need to be removed for the rest to have a chance at being parseable JavaScript if they aren't in strings or literals.  On the other hand, replacing them with something other than an empty string is just guesswork.  On the third hand, we can't lex every snippet between template tags separately, since that would miss any and all context.

So in these cases there's always a danger of misinterpretation, unfortunately - and JS's more than usually ambiguous syntax is not helping.

**Comment by boanergies** [comment]
Looking at it more this morning, would one possible solution be to change what we consider the needle to be for the JavaScriptDjango lexer into looking for both `Other` and `Preproc` tokens? My reasoning is particularly the django lexer is mainly pulling out all the template related stuff, so if we had the DelegatingLexer be on the look out for `Preproc` tokens it would at least indicate to the javascript lexer there is code between the statements.

**Comment by birkenfeld** [comment]
The problem is that when the JS lexer gets its pass, it doesn't see the template text at all.  `DelegatingLexer` works by pulling out all the things the first lexer (here `Django`) classifies as `Other`, concatting them, lexing them using the other lexer (here `Javascript`), and afterwards merging the token streams by inserting the Django tokens where they originally appeared.

**Comment by boanergies** [comment]
Right, and it only looks for `Other` because thats the default value set for the needle in the DelegatingLexer, if the needle was instead a tuple with `(Other, Preproc)` that would indicate at least to have a part of the template code passed to the javascript lexer.
My only concern would be if the JavascriptLexer would simply go over the template language or try to actually parse it which would probably create some errors.

**Comment by birkenfeld** [comment]
Feel free to experiment - I'm skeptical that anything generally correct can be done here.

**Comment by boanergies** [comment]
playing with this more, I realize this is actually correct functionality. I found for my problem its better sometimes to only run the javascript lexer versus the djangojavascript lexer. I'll go ahead and close the issue since this isn't actually a bug
