### ISSUE TITLE
Lexer request: add jsonc lexer

### ISSUE THREAD

**Issue by Mesteery** [pygments/pygments#1680]
Add a JSONC lexer, a basic JSON with comments (`// inline` and `/* block */`).

**Comment by Anteru** [comment]
@kurtmckee Does this sound like something you could look at?

**Comment by kurtmckee** [comment]
Yep! I saw the request earlier this week and mulled over whether to make this part of the default JSON lexer or not. Haven't reached a conclusion yet, though; I need to review the JSONC spec a little more.

**Comment by kurtmckee** [comment]
After review, it appears that every JSONC proposal (and there are multiple) is just an attempt to make a subset of Javascript into a superset of JSON.

In other words, Pygments' Javascript lexer appears to be more than sufficient to parse JSON with comments added.

[![image](https://user-images.githubusercontent.com/39996/107862800-ef697800-6e14-11eb-8a82-f77bf53484f5.png)](https://pygments.org/demo/?lexer=js&code=%7B%0A%2F%2F%20line%0A%22a%22%3A%201%2C%20%2F*%20multi%0Aline%20*%2F%20%22b%22%3A%203%0A%7D)

1. The Javascript lexer already parses JSON with comments.
2. No single proposal going by the name "JSONC" is a clear winner of the term.

For this reason, I recommend closing this ticket and directing users to use the full Javascript lexer.

**Comment by Anteru** [comment]
Perfect, thanks for checking. I wasn't aware you handle comments already -- and yes, it totally makes sense to not cater for various JSONC flavors if all they add are comments.

**Comment by alainpannetier** [comment]
Does that work?

{
   "a" : "b"
 }
 Is single colour in javascript and two-colours ("key": "value") in json.

 So javascript cannot work for json.

**Comment by kurtmckee** [comment]
@alainpannetier, you're correct that the object keys and string values are a single color in Javascript. This is because the Javascript lexer interprets anything in double quotes as a `String.Double` token. However, that does not mean that the Javascript lexer cannot be used for JSON. It just means the Javascript lexer could be improved so that it treats object keys as `Name.Tag` tokens.

As I wrote above, every specification that introduces comments in JSON (and there are many!) just introduces features that are already handled by the Javascript parser. Whether it's called "JSONC", "JSON-C", or "JSON5", it appears that each specification introduces comments and other things that make them something more than JSON...but something less than Javascript, which already supports all of their proposed features.

```
┌──────────────────────────────────┐
│            Javascript            │
│                                  │
│  ┌────────────────────────────┐  │
│  │    JSONC, JSON-C, JSON5    │  │
│  │                            │  │
│  │          ┌──────┐          │  │
│  │          │ JSON │          │  │
│  │          └──────┘          │  │
│  │                            │  │
│  └────────────────────────────┘  │
│                                  │
└──────────────────────────────────┘

```

My recommendation is to target an improvement to the Javascript parser.

**Comment by kurtmckee** [comment]
I've added comment support to JSON in #2049. It's not part of the JSON spec but adding it doesn't affect parsing of valid JSON documents.
