### ISSUE TITLE
How do you feel about being vendored in pip?

### ISSUE THREAD

**Issue by pradyunsg** [pygments/pygments#1953]
Hi there!

I'm one of the maintainers on pypa/pip, and we've been exploring ways to improve our output. One of the things I'm hoping to do is to utilize rich (which uses pygments as a dependency) for pip's CLI output needs. This, of course, means that we'd need to vendor pygments in pip ([our vendoring policy](https://pip.pypa.io/en/stable/development/vendoring-policy/)).

So... I'd like to make sure y'all are OK with us doing that!

This doesn't have too many implications, beyond a general agreement that this package will stay pure-Python and that you're OK with modifications we'd be making in our vendored copy (which we want to keep compatible with the original sources, so that it's a drop in replacement -- modulo changes needed to imports). Notably, in https://github.com/pypa/pip/pull/10462, I've been experimenting with tree-trimming parts of pygments that we won't use to make it a bit lighter (we're a bit mindful of our distribution sizes).

Let me know what you think and if you have any concerns with this! :)

**Comment by birkenfeld** [comment]
Hey Pradyun, I don't see problems with that; the only problem for the future might be a switch to the 3rd-party `regex` library. However, that's a quite monumental task that currently nobody has the time for.

As for trimming, since I assume you need highlighting mostly for Python code and a few other formats, you can aggressively remove modules in `pygments.lexers` that are unneeded; if you regenerate the mapfiles afterwards.

The condition from our side is that nobody can mistakenly use that copy of Pygments thinking it's the official one, but I assume that's ensured.

**Comment by pradyunsg** [comment]
Yea, it'll only be importable as `pip._vendor.pygments` -- which... well... no one else should mistake to be "official". :)

> the only problem for the future might be a switch to the 3rd-party regex library. 

That would indeed be problematic, if it became an unconditional dependency -- since pip can't depend on something that depends on compiled code (outside of the standard library).

My understanding is that `regex` is a drop-in replacement/backwards-compatible with `re`, so if/when this happens, if you could make it possible to continue using using pygments with just `re`, that would be ideal!

**Comment by birkenfeld** [comment]
> My understanding is that `regex` is a drop-in replacement/backwards-compatible with `re` so if/when this happens, if you could make it possible to continue using using pygments with just `re`, that would be ideal!

Well, that would kind of defeat the point since we'd want to make use of the improved features of `regex`. But as I said, right now this is not more than a twinkle in our eyes. And we could strive to keep the lexers compatible that you're using.

In any case I'd like @Anteru to also chip in with his opinion.

**Comment by Anteru** [comment]
While I'd love to switch to `regex` sooner rather than later I don't see it happening right now, given the current amount of maintenance work which is keeping us busy as-is. I would hope that we could support both, but as @birkenfeld said this kind of defeats the purpose as the main motivation to move to `regex` is to become more resilient against catastrophic backtracking.

The upshot is that we've been better recently in finding those cases when new lexers get added, so the value add of moving to `regex` is also somewhat limited as we have no _known_ cases of catastrophic backtracking. While this of course doesn't mean there isn't one, it's not an incredibly pressing issue. I'm fine with Pygments being a vendored library within `pip` as long as it's blindingly obvious that this is not the official Pygments, and ideally if `pip` does update after releases as we're doing new major releases quite regularly with big improvements on lexer fidelity, so if `pip` sticks around with an old version of Pygments for years this could leave a negative impression on the quality of Pygments.

**Comment by pradyunsg** [comment]
Neato!

Much like all the other packages that pip vendors, the vendored pygments would only be importable as `import pip._vendor.pygments` -- between the underscored name and explicit references to `pip` and `vendor` in the import name, I don't think there's any risk of this being percieved as "official", or being confused with a plain `import pygments`.

We update pip's vendored dependencies roughly every 3 months and like to stay compatible with the latest pygments releases, ideally without modifications beyond the namespace changes in the imports.

Regarding `regex`, I think it'd be fine to deal with that whole situation when it happens -- we'll know exactly what needs to be done to make things work at that time (i.e. the `regex` adoption has an open PR). :)

**Comment by pradyunsg** [comment]
Closing this out. Feel free to reopen this if you reckon there's more to discuss here. :)
