### ISSUE TITLE
Scala language support

### ISSUE THREAD

**Issue by yongqilei** [pygments/pygments#2037]
Hi, I'm using pygment in mkdocs-material,

I'm facing syntax highlight problems with language scala:

![image](https://user-images.githubusercontent.com/25628561/149776105-b9e0ab16-7f4c-4563-ad8a-b18fbc5c05bb.png)

All of the keywords are same color, only some numbers are highlighted.

> \```scala
> val doubled = for i <- ints yield i * 2     // style shown above
> val doubled = for (i <- ints) yield i * 2
> val doubled = for (i <- ints) yield (i * 2)
> val doubled = for { i <- ints } yield (i * 2)
> \```

If it's not a problem, could you please tell me how to use it correctly with scala?

Thank you so much!!

**Comment by Jean-Abou-Samra** [comment]
This works correctly for me on the command line.

![image](https://user-images.githubusercontent.com/37271310/152269540-9974e5d5-93f2-4957-b546-3e3933d0cfed.png)


Are you sure that you specified the language correctly? What is your configuration otherwise? This must be a problem either in your interaction with MkDocs or in its interaction with Pygments.

**Comment by Jean-Abou-Samra** [comment]
I'm assuming this has been fixed by specifying the language somewhere and closing; please reopen if the problem persists and you cannot find the answer in Mkdocs documentation.
