### ISSUE TITLE
How to write a lexer rule for a language with combined lines

### ISSUE THREAD

**Issue by kuenzign** [pygments/pygments#2052]
Many C-style languages use semicolons (`;`) as line endings.  This allows you to combine lines together as a single line.  For example:
```
string str1 = "text1";
string str2 = "text2";
```
can be combined into:
```
string str1 = "text1"; string str2 = "text2";
```

Is there a way to "truncate" the match text after a character such as a semicolon so that regexes that check for the beginning of a line using the caret (`^`) will consider that to be the start of the line.  For example, if I had a regex like `^\s*string`, I am looking for a way to make it match both instances of `string` in the above example (since they would match if the lines were actually separate).

Has anyone had to solve this issue in a lexer before?  Does anyone have any suggestions for what could be used?  I looked at using states for this, but there didn't seem to be a way to truncate the text so that text after a semicolon appears to be the start of a line.

**Comment by Anteru** [comment]
You could modify the token stream to achieve this, but I'm not sure if this is an XY problem here. What is the issue you're trying to solve which requires you to match the beginning of a line? Clearly in a language like C this won't work, due to constructs like:
```
const char* c = "\
  string str = c; \
";
```
or
```
{ string str2 = "text"; }
```

In all those cases a search for `string` at the beginning of the line will fail/produce incorrect results.
