### ISSUE TITLE
Docs: "nowrap" in HtmlFormatter

### ISSUE THREAD

**Issue by buhtz** [pygments/pygments#2396]
About removing the enclosing `<div>` tag you pointed me to here

https://github.com/pygments/pygments/discussions/2394#discussioncomment-5469859

where your users can find the term

> Wrapping can be disabled using the nowrap option.

In my understanding (as a non-nativ speaker) this is about making newlines or inserting newline chars in the strings. That his is about the enclosing div tag did come to my mind while reading this.

Maybe "to remove the enclosing div tag" (or pre also?) would be better?

**Comment by birkenfeld** [comment]
The effect of `nowrap` is explained a bit more below, in the list of all options, but we can do a better job describing it.

**Comment by buhtz** [comment]
> > And another point: The person who wrote code is responsible to document it.
> 
> Going by that logic, nobody would/should ever contribute documentation fixes.

A docu fix is different from documentation itself. My issue wasn't about fixing a little problem but writing a API docu. Again: The API of your package is not documented. There is no API docu (aka API Reference) for your project.

I have no problem to provide fixes to existing docu. But your project doesn't offer it.
And the Sphinx infrastructure make it not easy for contributors to contribute.

**Comment by Anteru** [comment]
I don't see us using "pydoctor" or any other _external_ documentation solution on top of Sphinx -- unless it happens to fit the existing documentation style/tooling, it's just extra work, and the API surface we document is _fairly_ small because you're not supposed to muck around with the majority of Pygments. Hence we use a lot of generated indices and so on, to make the presentation more useful to users (like our list of lexers or formatters.)

Also, keep in mind this is a long running project with many contributors. It's not always clear at _contribution time_ how much documentation is needed. It happens that some documentation strings are not great and need additional passes. In this case, it's fair to say the `HTMLFormatter` has grown _a lot_ over the years, and not every option added there was documented well and/or all interactions were documented. That's the underlying issue here. An API documentation wouldn't help you surface that -- the options are all visible here: https://pygments.org/docs/formatters/, so it's not a problem of not being able to find the documentation.

**Comment by buhtz** [comment]
> I don't see us using "pydoctor" or any other _external_ documentation solution on top of Sphinx

That is a misunderstanding about Sphinx. Sphinx and "other" tools (like pydoctor or doxygen) do not exist in the same continuum. It is apples and bananas. The "other" are real/full automatic tools. Sphinx is not. This is not a bug or disadvantage of Sphinx. It is just that Sphinx was never designed to be a autodoc tool. It is a doc tool, with some semi-auto features offering you much freedom about layout and content structure which also cost you a lot of resources to handle and maintain. A project/maintainer need to weight this freedom and resources against each other.

As a present and just to show you what could be possible I can offer you a quick n dirty pydoctor based docu of your own package in the attachment.
There is also the `hey_doc.py` script that I used to collect some meta data from the project and then run `pydoctor` via `subprocess.Popen()` with correct parameters. I needed to tweak the script a bit and [found some issues I will fix someday](https://codeberg.org/buhtz/buhtzology/issues/70).

Please rename the attachments suffix from `.zip` to `.7z`. Microsoft GitHub still do not know 7zip.
[pygments_docs_via_pydoctor.7z.zip](https://github.com/pygments/pygments/files/11111898/pygments_docs_via_pydoctor.7z.zip)

**Comment by birkenfeld** [comment]
Nice, thanks for the rework.
