### ISSUE TITLE
its hard to figure the -O options

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#424]
(Original issue 717 created by RonnyPfannschmidt on 2011-12-03T15:40:01.735528+00:00)

i had to read code to figure how to declare stuff like input/output encodings

this needs doc enhancements

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-02T03:23:22.654330+00:00)

Agreed, I do as well.  Do you have ideas how we can make it better?

**Comment by kurtmckee** [comment]
It appears that the documentation has been improved since this ticket was created.

There may be an improvement opportunity in the [command line interface documentation](https://pygments.org/docs/cmdline/) to mention that lexer and formatter options match the option names listed in the [lexer](https://pygments.org/docs/lexers/) and [formatter](https://pygments.org/docs/formatters/) documentation.

However, this ticket is nine years old and it seems like it's no longer necessary to read code to understand how to use the CLI. I recommend closing this ticket.
